#  menu items
[[main]]
  name = "ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰"
  weight = 1
  url = "jp/downloads/"

[[main]]
  name = "ãƒ‰ãƒƒã‚¯ã‚¹"
  weight = 2
  url = "jp/docs/ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒ†ãƒ¼ã‚·ãƒ§ãƒ³"

[[main]]
  name = "ç§ãŸã¡ã«ã¤ã„ã¦"
  weight = 3
  url = "jp/about"

[[main]]
  name = "ğŸ‡ºğŸ‡¸"
  weight = 4
  url = "en/"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"